services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3010:3000 # 起動するポート番号を変更するため
    environment:
      - WATCHPACK_POLLING=true # ホットモジュールリロードをするため
    env_file:
      - ./frontend/.env # frontendフォルダの配下でenvファイルを使用するため
  db:
    image: mysql:8.2.0
    platform: linux/amd64
    container_name: mysql-container
    expose:
      - “3306”
    env_file:
      - .env
    volumes:
      - ./settings/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  db-store:
